version: '3'

services:
  web:
    build: .
    container_name: django
    volumes:
      - .:/usr/src/Desktop/acme
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - TOKEN
    ports:
      - 8000:8000

    command:
      sh -c "python3 manage.py makemigrations && 
      python3 manage.py migrate && 
      python3 manage.py runserver 0.0.0.0:8000"

    depends_on:
      - pgdb

  pgdb:
    image: postgres:16.3
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    ports:
      - 5432:5432
volumes:
  pgdbdata: null