# Generated by Django 4.2.13 on 2024-06-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('M', 'Milk'), ('D', 'Drinks'), ('B', 'Bakery'), ('MT', 'Meat'), ('V', 'Vegeterian'), ('H', 'Halal')], max_length=10)),
                ('in_stock', models.BooleanField(default=False)),
            ],
        ),
    ]
